### ISSUE TITLE
Ошибка получения цены

### ISSUE THREAD

**Issue by GooseBumpsOS** [rkashigin/crypto-checker#1]
https://github.com/rkashigin/crypto-checker/blob/bc3f8961c5f08749d8e469cf90d6012a89e3294f/routes/check.routes.js#L18

Вместо получения цены, вы получаете объем

![image](https://user-images.githubusercontent.com/32247640/98940044-6da73d00-24fb-11eb-9238-d3fa2a57fe84.png)

**Comment by rkashigin** [comment]
Спасибо!
Все исправил.
